# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('constellationID', models.IntegerField(primary_key=True, serialize=False)),
                ('constellationName', models.CharField(db_index=True, max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('xMax', models.FloatField()),
                ('xMin', models.FloatField()),
                ('yMax', models.FloatField()),
                ('yMin', models.FloatField()),
                ('zMax', models.FloatField()),
                ('zMin', models.FloatField()),
                ('factionID', models.IntegerField(null=True)),
                ('radius', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regionID', models.IntegerField(primary_key=True, serialize=False)),
                ('regionName', models.CharField(db_index=True, max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('xMax', models.FloatField()),
                ('xMin', models.FloatField()),
                ('yMax', models.FloatField()),
                ('yMin', models.FloatField()),
                ('zMax', models.FloatField()),
                ('zMin', models.FloatField()),
                ('factionID', models.IntegerField(null=True)),
                ('radius', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='constellation',
            name='regionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evesde.Region'),
        ),
    ]
