# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evesde', '0004_auto_20161017_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constellation',
            name='radius',
            field=models.FloatField(null=True),
        ),
    ]
