# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evesde', '0005_auto_20161017_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarsystem',
            name='constellation',
            field=models.NullBooleanField(),
        ),
    ]
