# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evesde', '0007_auto_20161017_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvCategory',
            fields=[
                ('categoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(db_index=True, max_length=100)),
                ('iconID', models.IntegerField()),
                ('published', models.NullBooleanField()),
            ],
        ),
    ]
