# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evesde', '0008_invcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invcategory',
            name='categoryName',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invcategory',
            name='iconID',
            field=models.IntegerField(null=True),
        ),
    ]
