# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evesde', '0009_auto_20161018_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvGroup',
            fields=[
                ('groupID', models.IntegerField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(db_index=True, max_length=100)),
                ('iconID', models.IntegerField(null=True)),
                ('useBasePrice', models.NullBooleanField()),
                ('anchored', models.NullBooleanField()),
                ('anchorable', models.NullBooleanField()),
                ('fittableNonSingleton', models.NullBooleanField()),
                ('published', models.NullBooleanField()),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evesde.InvCategory')),
            ],
        ),
    ]
