# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evesde', '0010_invgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvType',
            fields=[
                ('typeID', models.IntegerField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(db_index=True, max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('mass', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('capacity', models.FloatField(null=True)),
                ('portionSize', models.IntegerField(null=True)),
                ('raceID', models.IntegerField(null=True)),
                ('basePrice', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('published', models.NullBooleanField()),
                ('marketGroupID', models.IntegerField(db_index=True, null=True)),
                ('iconID', models.IntegerField(null=True)),
                ('soundID', models.IntegerField(null=True)),
                ('graphicID', models.IntegerField(null=True)),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evesde.InvGroup')),
            ],
        ),
    ]
