# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evesde', '0011_invtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvMarketGroup',
            fields=[
                ('marketGroupID', models.IntegerField(primary_key=True, serialize=False)),
                ('marketGroupName', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=3000)),
                ('iconID', models.IntegerField(null=True)),
                ('hasTypes', models.NullBooleanField()),
                ('parentGroupID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evesde.InvMarketGroup')),
            ],
        ),
        migrations.AlterField(
            model_name='invtype',
            name='marketGroupID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evesde.InvMarketGroup'),
        ),
    ]
