# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evesde', '0014_auto_20161019_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invmarketgroup',
            name='description',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
