# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evesde', '0017_auto_20161019_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapDenormalize',
            fields=[
                ('itemID', models.IntegerField(primary_key=True, serialize=False)),
                ('orbitID', models.IntegerField(null=True)),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('z', models.FloatField(null=True)),
                ('radius', models.FloatField(null=True)),
                ('itemName', models.CharField(max_length=100, null=True)),
                ('security', models.FloatField(null=True)),
                ('celestialIndex', models.IntegerField(null=True)),
                ('orbitIndex', models.IntegerField(null=True)),
                ('constellationID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evesde.Constellation')),
                ('groupID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evesde.InvGroup')),
                ('regionID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evesde.Region')),
                ('solarSystemID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evesde.SolarSystem')),
                ('typeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evesde.InvType')),
            ],
        ),
    ]
